# Generated by Django 4.2.7 on 2023-11-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_casino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=123, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
