# Generated by Django 4.2.7 on 2023-11-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_casino', '0002_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField()),
                ('ranking_position', models.PositiveIntegerField()),
                ('reliability', models.FloatField()),
                ('speed', models.FloatField()),
                ('payout', models.FloatField()),
                ('player_rating', models.FloatField()),
                ('editor_rating', models.FloatField()),
                ('casino_text', models.TextField()),
                ('promo_text', models.TextField()),
                ('promo_code', models.CharField(max_length=50)),
                ('payments_images', models.URLField()),
                ('providers_images', models.URLField()),
                ('interface_languages_image', models.URLField()),
                ('countries_access', models.TextField()),
            ],
        ),
    ]
