# Generated by Django 4.2.7 on 2023-11-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_casino', '0003_casinoprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceLanguagesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='casinoprofile',
            name='interface_languages_image',
        ),
        migrations.RemoveField(
            model_name='casinoprofile',
            name='payments_images',
        ),
        migrations.RemoveField(
            model_name='casinoprofile',
            name='providers_images',
        ),
        migrations.AddField(
            model_name='casinoprofile',
            name='interface_languages_image',
            field=models.ManyToManyField(to='site_casino.interfacelanguagesimage'),
        ),
        migrations.AddField(
            model_name='casinoprofile',
            name='payments_images',
            field=models.ManyToManyField(to='site_casino.paymentimage'),
        ),
        migrations.AddField(
            model_name='casinoprofile',
            name='providers_images',
            field=models.ManyToManyField(to='site_casino.providerimage'),
        ),
    ]
