# Generated by Django 4.2.7 on 2023-11-16 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_casino', '0004_interfacelanguagesimage_paymentimage_providerimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casinoprofile',
            name='interface_languages_image',
        ),
        migrations.RemoveField(
            model_name='casinoprofile',
            name='payments_images',
        ),
        migrations.RemoveField(
            model_name='casinoprofile',
            name='providers_images',
        ),
        migrations.AddField(
            model_name='casinoprofile',
            name='interface_languages_image',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='site_casino.interfacelanguagesimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casinoprofile',
            name='payments_images',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='site_casino.paymentimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casinoprofile',
            name='providers_images',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='site_casino.providerimage'),
            preserve_default=False,
        ),
    ]
