# Generated by Django 4.2.7 on 2023-11-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_casino', '0006_alter_casinoprofile_interface_languages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinoprofile',
            name='interface_languages_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='casinoprofile',
            name='payments_images',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='casinoprofile',
            name='providers_images',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='InterfaceLanguagesImage',
        ),
        migrations.DeleteModel(
            name='PaymentImage',
        ),
        migrations.DeleteModel(
            name='ProviderImage',
        ),
    ]
