# Generated by Django 4.2.7 on 2023-11-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_casino', '0009_casinocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinocomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_casino.userprofile'),
        ),
    ]
