# Generated by Django 4.2.7 on 2023-11-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_casino', '0011_casinocomment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinocomment',
            name='rating',
            field=models.FloatField(),
        ),
    ]
