# Generated by Django 4.2.7 on 2023-12-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_casino', '0014_casinoprofile_casino_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinoprofile',
            name='promo_code',
            field=models.TextField(),
        ),
    ]
