# Generated by Django 4.2.7 on 2023-12-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_casino', '0016_gameprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='sorting_criteria',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
