# Generated by Django 4.2.7 on 2023-12-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_casino', '0017_gameprofile_sorting_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='platforms',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='volatility',
            field=models.CharField(max_length=100),
        ),
    ]
