# Generated by Django 4.2.7 on 2023-12-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_casino', '0018_alter_gameprofile_platforms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='release_date',
            field=models.CharField(max_length=50),
        ),
    ]
